######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 11 15:07:45 2014
######################################################################

TEMPLATE = app
TARGET = qt
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit
QT += widgets
QT += webkitwidgets
# Input
SOURCES += main.cpp
